const ActionType = {
  ADD_TODO: "ADD_TODO",
  DELETE_TODO: "[Delete] DELETE_TODO",
  EDIT_TODO: "[Edit] EDIT_TODO",
  SWITCH_TODO_STATUS: "SWITCH_TODO_STATUS",
  FILTER_BY_TEXT: "FILTER_BY_TEXT",
  FILTER_BY_STATUS: "FILTER_BY_STATUS",
  FILTER_BY_PRIORITY: "FILTER_BY_PRIORITY",
};

export default ActionType;
